modLoader = "javafml"
loaderVersion = "[0,)"
license = "GPL-3.0-only"
logoFile = "logo.png"

[[mods]]
modId = "chitin"
version = "1"
displayName = "Chitin Tools and Armor"
authors = "WillT608"
description = '''This mod adds a set of tools and armor made from chitin.'''

[[dependencies.chitin]]
modId = "forge"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chitin]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2]"
ordering = "NONE"
side = "BOTH"